/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.swing.pkg01;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class Questao2Exercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Questao2Exercicio2
     */
    public Questao2Exercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbZeroADois = new javax.swing.JLabel();
        tfZeroADois = new javax.swing.JTextField();
        lbTresASete = new javax.swing.JLabel();
        tfTresASete = new javax.swing.JTextField();
        lbOitoAQuinze = new javax.swing.JLabel();
        tfOitoAQuinze = new javax.swing.JTextField();
        btCalculo = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbZeroADois.setText("Filhos de 0 a 2 anos:");

        lbTresASete.setText("Filhos de 3 a 7 anos:");

        lbOitoAQuinze.setText("Filhos de 8 a 15 anos:");

        btCalculo.setText("Calcula bolsa");
        btCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculoActionPerformed(evt);
            }
        });

        lbResultado.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultado)
                    .addComponent(btCalculo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbZeroADois)
                            .addGap(18, 18, 18)
                            .addComponent(tfZeroADois, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTresASete)
                                .addComponent(lbOitoAQuinze))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTresASete, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addComponent(tfOitoAQuinze)))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbZeroADois)
                    .addComponent(tfZeroADois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTresASete)
                    .addComponent(tfTresASete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOitoAQuinze)
                    .addComponent(tfOitoAQuinze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btCalculo)
                .addGap(39, 39, 39)
                .addComponent(lbResultado)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculoActionPerformed
        lbResultado.setForeground(Color.BLUE);
        
        Integer zeroAdois = Integer.valueOf(tfZeroADois.getText());
        Integer tresAsete = Integer.valueOf(tfTresASete.getText());
        Integer oitoAquinze = Integer.valueOf(tfOitoAQuinze.getText());
        
        Double soma1 = zeroAdois * 15.50;
        Double soma2 = tresAsete * 10.00;
        Double soma3 = oitoAquinze * 5.50;
        Double contaFinal = soma1+soma2+soma3;
        
        String resultado = String.format("Sua bolsa kids será de %.2f",contaFinal);
        lbResultado.setText(resultado);
        
        
    }//GEN-LAST:event_btCalculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questao2Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questao2Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questao2Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questao2Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questao2Exercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculo;
    private javax.swing.JLabel lbOitoAQuinze;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbTresASete;
    private javax.swing.JLabel lbZeroADois;
    private javax.swing.JTextField tfOitoAQuinze;
    private javax.swing.JTextField tfTresASete;
    private javax.swing.JTextField tfZeroADois;
    // End of variables declaration//GEN-END:variables
}
